apiVersion: v1
kind: Service
metadata:
  name: canisweb
  labels:
    app: canis
spec:
  selector:
    app: canis
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"
